// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }




import type { Metadata } from "next";
import { ReactNode } from "react";
import MainRootLayout from "./Layoutbase";

export const metadata: Metadata = {
  title: "Thesis Manager",
  description: "Plateforme de gestion de thèses et mémoires",
};

export default function Layout({children}:{children:ReactNode}){
  return(
    <MainRootLayout>{children}</MainRootLayout>
  )
}